repos:
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v0.9.1
  hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
- repo: https://github.com/python/black
  rev: 19.10b0
  hooks:
    - id: black
      name: "Autoformat python files"
      types: [python]
      language_version: python3
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.9
  hooks:
    - id: flake8
      name: "Lint python files"
      types: [python]
      language_version: python3
      additional_dependencies: ['flake8-bugbear==19.8.0']
- repo: https://github.com/timothycrosley/isort
  rev: 4.3.21
  hooks:
    - id: isort
      name: "Sort python imports"
      types: [python]
      language_version: python3
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.740
  hooks:
    - id: mypy
      name: "Type-check python in src/"
      files: src/.*$
      types: [python]
    - id: mypy
      name: "Type-check python in tests/"
      files: tests/.*$
      types: [python]
